baseurl = "https://reganryannz.github.io/"
languageCode = "en-us"
title = "Code like a Walrus"
theme = "hyde"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
[params]
  themeColor = "theme-base-08"
  description = "If you finish a project and say \"If I did that again, I'd do it differently\"—that means you learned something."
